# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Post',
        ),
    ]
